# Generated by Django 5.1.7 on 2025-04-22 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=150, verbose_name='patronymic'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=18, validators=[django.core.validators.RegexValidator(message='Номер должен быть в формате: +7 (XXX) XXX-XX-XX', regex='^\\+7\\s?\\(?\\d{3}\\)?\\s?\\d{3}-\\d{2}-\\d{2}$')], verbose_name='Phone Number'),
        ),
    ]
