# Generated by Django 5.1.7 on 2025-04-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_full_name_user_patronymic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('broker', 'Broker'), ('developer', 'Developer')], default='client', max_length=10, verbose_name='User Type'),
        ),
    ]
