# Generated by Django 5.1.7 on 2025-04-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='Phone Number'),
        ),
    ]
