# Generated by Django 5.2 on 2025-04-30 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_property_favorite_contactrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='broker',
        ),
        migrations.AddField(
            model_name='favorite',
            name='favorite_type',
            field=models.CharField(choices=[('client', 'Клиентский'), ('broker', 'Брокерский')], default='client', max_length=10),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_received_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_sent_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.property'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
