# Generated by Django 5.1.7 on 2025-04-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='Горячее предложение'),
        ),
    ]
